### ISSUE TITLE
Generic Clock Controller clarification

### ISSUE THREAD

**Issue by adamgarbo** [mattb1969/InterruptswithRTCandWDT#1]
Hi @mattb1969,

Thanks for your example code illustrating how to use the SAMD21 RTC and WDT in conjunction with one another. I've made use of similar WDT code for a number of years, but always with an external RTC. 

Recently, I've started using the SAMD21's internal RTC and realized that the RTCZero library is using the same Generic Clock Controller 2 that is commonly used in the WDT code. In your example, I see you're specifying GCLK1 for use with the RTC.

https://github.com/mattb1969/InterruptswithRTCandWDT/blob/40672268b57a2a74b5eeb05d516baa68bd618de7/src/main.cpp#L125-L128

As I'd like to continue using RTCZero, would it be just as easy to swap the WDT over to using GCLK1 instead? For example: https://github.com/adamgarbo/Cryologger_Iceberg_Tracking_Beacon/blob/9fa9059545e0a94f135825e393e949ed47cb968c/Software/cryologger_itb_adafruit/02_wdt.ino#L1-L34

Edit: Am I correct in assuming that the RTC and WDT must use different GCLKs if you want them configured for use with separate clock sources?

Cheers,
Adam

**Comment by mattb1969** [comment]
Hi Adam,
Sorry it has taken me so long to get back to you.

To try and answer your questions in reverse. It is advisable to use use different GLCKs for the RTC and WDT. I found that because of the divisor and the setup, it was easier that way. I checked the power consumption and although it is slightly higher, it is not significant.

Secondly, it is not that difficult to switch which GLCK is being used, if you follow my code, you can probably see the bits I used to set the GLCKs. I suspect if you compare my configuration to that of the RTCZero library, you’ll spot the differences and if you also refer to the documentation for the chip, you’ll see why they are different.

Finally, why do you want to swap? I started with RTCZero, but finally gave up using others libraries as I kept having issues, things like incorrect timers, WDT not working and RTC timing being all over the place. I really struggled to get it to work, hence I went right back to the beginning and wrote my own. It really gave me insight as to how to configure the clocks to get the results I was after and the capability of the SAMD21.

Hope this helps, but please do get back in touch if you have any further questions. I’ll do my best to help with them

Matthew

**Comment by adamgarbo** [comment]
Hi Matthew,

Thanks for getting back to me about this. 

I spent some some additional time researching the issue and realized that it was possible to feed the same GCLK2 to both the  RTC and the WDT. The RTCZero library uses the external crystal XOSC32K and divides it down to the same 1.024 kHz, and since the GLCK is constantly running anyway, it made sense to take advantage of it for the WDT timing. I simply initialize the RTCZero library first, and then configure the WDT (minus the GCLK configuration). The [code](https://github.com/adamgarbo/Cryologger_Iceberg_Tracking_Beacon/blob/6ad4f82b0367b73e52199e47f9f8f9aba2925d84/Software/cryologger_itb_adafruit/02_wdt.ino#L1-L35) has been working reliably over the past couple of weeks of testing.

Regarding the reason for the swap, in my previous instrument designs, I've made use of the Maxim Integrated DS3231SN external RTC for timing functionality. Recently, I've determined that the SAMD21's internal RTC coupled with a GPS that  periodically syncs the RTC, is just as reliable (if not more so). This also has the benefit if reducing the component count and power consumption.

Thanks again for your help!
Adam
